version: "3.8"

x-database-credentials: &database-credentials
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: db

services:
  postgres:
    container_name: postgres
    image: postgres:15.3
    environment:
      <<: *database-credentials
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
